export enum RolesEnum {
  ROLE_ROOT = 'ROLE_ROOT',
  ROLE_SUPPORT = 'ROLE_SUPPORT',
  ROLE_RESELLER = 'ROLE_RESELLER',
  ROLE_SOFTWARE = 'ROLE_SOFTWARE',
  ROLE_COMPANY = 'ROLE_COMPANY',
  ROLE_CUSTOMER = 'ROLE_CUSTOMER',
  ROLE_OFFICE_MANAGER = 'ROLE_OFFICE_MANAGER',
  ROLE_OFFICE_SUPERVISOR = 'ROLE_OFFICE_SUPERVISOR',
  ROLE_OFFICE_ANALYST = 'ROLE_OFFICE_ANALYST',
  ROLE_OFFICE_AUXILIARY = 'ROLE_OFFICE_AUXILIARY',
}
